wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.9
      5: 0.10.28
      8:
      - 5
architecture:
  desc: null
  value: MAC
bert:
  desc: null
  value: false
controlPostDropout:
  desc: null
  value: 1.0
controlPreDropout:
  desc: null
  value: 1.0
dataset:
  desc: null
  value: GQA
encInputDropout:
  desc: null
  value: 0.2
encStateDropout:
  desc: null
  value: 0.0
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0001
max_step:
  desc: null
  value: 5
memoryDropout:
  desc: null
  value: 0.15
objects:
  desc: null
  value: false
outputDropout:
  desc: null
  value: 0.85
qDropout:
  desc: null
  value: 0.08
qDropoutOut:
  desc: null
  value: 0
readDropout:
  desc: null
  value: 0.15
spatial:
  desc: null
  value: true
stemDropout:
  desc: null
  value: 0.2
subset_train:
  desc: null
  value: 200000
version:
  desc: null
  value: spatial
wordEmbDropout:
  desc: null
  value: 1.0
writeDropout:
  desc: null
  value: 1.0
